import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import { Shield, Lock, Eye, FileText, Info, Users, Database, Trash2, Mail, ExternalLink, Scale } from 'lucide-react';

const PrivacyPolicy = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const sections = [
        {
            icon: <Info size={24} />,
            title: "Interpretation and Definitions",
            content: (
                <div className="policy-text">
                    <h3>Interpretation</h3>
                    <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    <h3 style={{ marginTop: '1.5rem' }}>Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="policy-list">
                        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Application</strong> refers to homeit, the software program provided by the Company.</li>
                        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our") refers to thehomeit.</li>
                        <li><strong>Cookies</strong> are small files placed on Your computer or mobile device, containing details of Your browsing history.</li>
                        <li><strong>Country</strong> refers to: Haryana, India.</li>
                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service</strong> refers to the Application or the Website or both.</li>
                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure.</li>
                    </ul>
                </div>
            )
        },
        {
            icon: <Database size={24} />,
            title: "Collecting and Using Your Personal Data",
            content: (
                <div className="policy-text">
                    <h3>Types of Data Collected</h3>
                    <h4 className="sub-heading">Personal Data</h4>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information: Email address, First name and last name, Phone number, and Address details.</p>

                    <h4 className="sub-heading">Usage Data</h4>
                    <p>Collected automatically when using the Service. May include IP address, browser type, browser version, pages visited, time spent, and unique device identifiers.</p>

                    <h4 className="sub-heading">Information from Camera and Photo Library</h4>
                    <p>While using Our Application, We may collect pictures and other information from your Device's camera and photo library with Your prior permission.</p>
                </div>
            )
        },
        {
            icon: <Eye size={24} />,
            title: "Tracking Technologies and Cookies",
            content: (
                <div className="policy-text">
                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies for purposes like Necessary/Essential Cookies, Cookies Policy Acceptance, and Functionality Cookies.</p>
                    <p>You can instruct Your browser to refuse all Cookies, but some parts of our Service may not function correctly.</p>
                </div>
            )
        },
        {
            icon: <Scale size={24} />,
            title: "Use and Disclosure of Data",
            content: (
                <div className="policy-text">
                    <p>The Company may use Personal Data to provide and maintain our Service, manage Your Account, perform contracts, contact You, and for business transfers or other purposes like data analysis.</p>
                    <p>We may share Your Personal Data with Service Providers, Affiliates, business partners, or other users with Your consent.</p>
                </div>
            )
        },
        {
            icon: <Users size={24} />,
            title: "Retention and Transfer",
            content: (
                <div className="policy-text">
                    <p>We retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy (e.g., Account Info up to 24 months after closure, Support Data up to 24 months).</p>
                    <p>Your information may be transferred to and maintained on computers located outside of Your jurisdiction where data protection laws may differ.</p>
                </div>
            )
        },
        {
            icon: <Trash2 size={24} />,
            title: "Your Rights and Security",
            content: (
                <div className="policy-text">
                    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. We strive to use commercially reasonable means to protect Your Personal Data, but no method of transmission is 100% secure.</p>
                </div>
            )
        }
    ];

    return (
        <div style={{ paddingTop: '140px', minHeight: '100vh', background: 'var(--bg-color)', paddingBottom: '120px' }}>
            <style>
                {`
                    .policy-text p { color: var(--text-secondary); line-height: 1.8; margin-bottom: 1.2rem; font-size: 1.05rem; }
                    .policy-text h3 { color: var(--text-primary); margin-bottom: 1rem; font-size: 1.4rem; font-weight: 700; letter-spacing: -0.01em; }
                    .sub-heading { color: var(--text-primary); margin: 1.5rem 0 0.8rem 0; font-size: 1.1rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
                    .policy-list { margin-left: 1.5rem; margin-top: 1rem; list-style-type: none; }
                    .policy-list li { color: var(--text-secondary); margin-bottom: 0.8rem; position: relative; padding-left: 1.5rem; }
                    .policy-list li::before { content: "•"; color: var(--accent-color); position: absolute; left: 0; font-weight: bold; }
                    .policy-text strong { color: var(--text-primary); font-weight: 600; }
                    .policy-text a { color: var(--accent-color); text-decoration: none; transition: opacity 0.2s; }
                    .policy-text a:hover { opacity: 0.8; }
                `}
            </style>
            <div className="container">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, ease: "easeOut" }}
                    style={{ textAlign: 'center', marginBottom: '6rem' }}
                >
                    <span style={{
                        color: 'var(--accent-color)',
                        textTransform: 'uppercase',
                        letterSpacing: '0.3em',
                        fontSize: '0.8rem',
                        fontWeight: 700,
                        marginBottom: '1rem',
                        display: 'block'
                    }}>Legal Document</span>
                    <h1 className="hero-title gradient-text" style={{ fontSize: '4.5rem', marginBottom: '1.5rem', lineHeight: 1.1 }}>
                        Privacy Policy
                    </h1>
                    <p className="hero-subtitle" style={{ margin: '0 auto', fontSize: '1.2rem', opacity: 0.7 }}>
                        Last updated: March 13, 2026
                    </p>
                    <div style={{
                        maxWidth: '850px',
                        margin: '3rem auto',
                        padding: '2.5rem',
                        borderRadius: '24px',
                        background: 'rgba(255,255,255,0.02)',
                        border: '1px solid var(--glass-border)',
                        color: 'var(--text-secondary)',
                        lineHeight: 1.8,
                        fontSize: '1.15rem'
                    }}>
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    </div>
                </motion.div>

                <div style={{
                    display: 'grid',
                    gridTemplateColumns: '1fr',
                    gap: '3rem',
                    maxWidth: '1000px',
                    margin: '0 auto'
                }}>
                    {sections.map((section, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 40 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true, margin: "-50px" }}
                            transition={{ duration: 0.6, delay: index * 0.1 }}
                            className="glass"
                            style={{
                                padding: '4rem',
                                borderRadius: '32px',
                                background: 'linear-gradient(135deg, rgba(255,255,255,0.04) 0%, rgba(255,255,255,0.01) 100%)',
                            }}
                        >
                            <div style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '1.8rem',
                                marginBottom: '3rem',
                                paddingBottom: '2rem',
                                borderBottom: '1px solid rgba(255,255,255,0.05)'
                            }}>
                                <div style={{
                                    background: 'linear-gradient(135deg, var(--accent-color), var(--accent-secondary))',
                                    padding: '1rem',
                                    borderRadius: '16px',
                                    color: 'white',
                                    display: 'flex',
                                    boxShadow: '0 10px 25px rgba(99, 102, 241, 0.25)'
                                }}>
                                    {section.icon}
                                </div>
                                <h2 style={{ fontSize: '2rem', fontWeight: 800, letterSpacing: '-0.03em' }}>
                                    {section.title}
                                </h2>
                            </div>
                            {section.content}
                        </motion.div>
                    ))}
                </div>

                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="glass"
                    style={{
                        maxWidth: '1000px',
                        margin: '6rem auto 0 auto',
                        padding: '5rem 4rem',
                        borderRadius: '40px',
                        textAlign: 'center',
                        background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.08) 0%, rgba(139, 92, 246, 0.05) 100%)',
                        border: '1px solid rgba(99, 102, 241, 0.15)',
                        boxShadow: '0 30px 60px -12px rgba(0,0,0,0.5)'
                    }}
                >
                    <div style={{
                        width: '80px',
                        height: '80px',
                        background: 'rgba(99, 102, 241, 0.1)',
                        borderRadius: '50%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        margin: '0 auto 2rem auto',
                        color: 'var(--accent-color)'
                    }}>
                        <Mail size={36} />
                    </div>
                    <h2 style={{ fontSize: '2.5rem', marginBottom: '1.2rem', fontWeight: 800, letterSpacing: '-0.04em' }}>Questions?</h2>
                    <p style={{
                        color: 'var(--text-secondary)',
                        marginBottom: '3rem',
                        fontSize: '1.2rem',
                        maxWidth: '600px',
                        margin: '0 auto 3rem auto',
                        lineHeight: 1.7
                    }}>
                        If you have any questions about this Privacy Policy, You can contact us directly at:
                    </p>
                    <a href="mailto:yugverma05@gmail.com" className="btn-primary" style={{
                        display: 'inline-flex',
                        padding: '1.4rem 4rem',
                        textDecoration: 'none',
                        borderRadius: '100px',
                        fontSize: '1.1rem',
                        letterSpacing: '0.02em'
                    }}>
                        yugverma05@gmail.com
                    </a>
                </motion.div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
